import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "./_components/footer/Footer";
import Header from "./_components/header/Header";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "700", "800", "900", "300", "600", "500"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Bizlicle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
